# Generated by Django 2.0.2 on 2018-03-13 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_general_answers',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('marital_status', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced'), ('widowed', 'widowed')], max_length=8)),
                ('zipcode', models.IntegerField()),
                ('num_kids', models.IntegerField()),
                ('annual_income', models.IntegerField()),
                ('spouse_annual_income', models.IntegerField()),
                ('health', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Meh', 'Meh'), ('Poor', 'Poor')], max_length=9)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
