# Generated by Django 2.0.2 on 2018-03-13 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_kids',
            fields=[
                ('kid', models.IntegerField(primary_key=True, serialize=False)),
                ('kid_age', models.IntegerField()),
                ('will_pay_for_college', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='user_life_answers',
            fields=[
                ('mortgage_balance', models.IntegerField()),
                ('other_debts_balance', models.IntegerField()),
                ('existing_life_insurance', models.IntegerField()),
                ('balance_investings_savings', models.IntegerField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user_kids',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
