# Generated by Django 2.0.2 on 2018-03-14 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_disability_plan_costs_health_plan_costs_life_plan_costs_user_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='health_question_options',
            fields=[
                ('health_question_option_id', models.IntegerField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=500)),
                ('high_deductible', models.FloatField()),
                ('low_deductible', models.FloatField()),
                ('HMO', models.FloatField()),
                ('PPO', models.FloatField()),
                ('HSA', models.FloatField()),
                ('critical_illness', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='health_questions',
            fields=[
                ('health_question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('high_deductible_total', models.IntegerField()),
                ('low_deductible_total', models.IntegerField()),
                ('HMO_total', models.IntegerField()),
                ('PPO_total', models.IntegerField()),
                ('HSA_total', models.IntegerField()),
                ('critical_illness_accident_policy_total', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='health_question_options',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.health_questions'),
        ),
    ]
