# Generated by Django 2.0.2 on 2018-03-14 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_health_questions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_health_questions_answer',
            name='q_1',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.health_question_options'),
        ),
    ]
