# Generated by Django 2.0.2 on 2018-03-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_health_questions_answer_q_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_question_options',
            name='question',
            field=models.CharField(default='', max_length=500),
        ),
    ]
