# Generated by Django 2.0.2 on 2018-03-30 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180329_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_health_questions_answer',
            name='q_10',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.health_question_options'),
        ),
        migrations.AddField(
            model_name='user_health_questions_answer',
            name='q_11',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.health_question_options'),
        ),
        migrations.AddField(
            model_name='user_health_questions_answer',
            name='q_12',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.health_question_options'),
        ),
        migrations.AddField(
            model_name='user_health_questions_answer',
            name='q_2',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.health_question_options'),
        ),
        migrations.AddField(
            model_name='user_health_questions_answer',
            name='q_3',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.health_question_options'),
        ),
        migrations.AddField(
            model_name='user_health_questions_answer',
            name='q_4',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.health_question_options'),
        ),
        migrations.AddField(
            model_name='user_health_questions_answer',
            name='q_5',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.health_question_options'),
        ),
        migrations.AddField(
            model_name='user_health_questions_answer',
            name='q_6',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.health_question_options'),
        ),
        migrations.AddField(
            model_name='user_health_questions_answer',
            name='q_7',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.health_question_options'),
        ),
        migrations.AddField(
            model_name='user_health_questions_answer',
            name='q_8',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.health_question_options'),
        ),
        migrations.AddField(
            model_name='user_health_questions_answer',
            name='q_9',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.health_question_options'),
        ),
    ]
